### ISSUE TITLE
How to run in Rust

### ISSUE THREAD

**Issue by Pelps12** [octoml/triton-client-rs#1]
SOrry I'm a bit new to rust and I don't know how I'd put this in the main function

**Comment by robo-corg** [comment]
Would an example help here?

**Comment by Pelps12** [comment]
Yes. An example with context of the main function that runs it. I don't know if I run it with futures or with tokio::main

**Comment by robo-corg** [comment]
I added an example in https://github.com/octoml/triton-client-rs/blob/main/examples/repo_index.rs hopefully that helps! It might also be worth looking at the tokio tutorial: https://tokio.rs/tokio/tutorial
